#!/bin/tcsh -f 


foreach target ("ione" "itwo" "ithree" "ifour" "ifive" "isix" "iseven")
	make $target
end
	
foreach target ("one" "two" "three" "four" "five" "six" "seven" "eight" "nine")
	make neat
	make $target
	make test
end

make distclean


